#!/bin/bash

m_help() {
	echo "sapphire-butler, a butler for Sapphire Linux."
	echo
	echo "This program has preconfigured tasks that are categorized into"
	echo "departments."
	echo
   	echo "Copyright (C) 2021 Matthew Evan"
	echo
	echo "This program is free software; you can redistribute it and/or modify"
   	echo "under the terms of the GNU General Public License as published by"
   	echo "Free Software Foundation; either version 3 of the License, or"
	echo "(at your option) any later version."
	echo
	echo "This program is distributed in the hope that it will be useful,"
	echo "but WITHOUT ANY WARRANTY; without even the implied warranty of"
	echo "MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the"
	echo "GNU General Public License for more details."
	echo
	echo "You should have received a copy of the GNU General Public License"
	echo "along with this program; if not, write to the Free Software Foundation,"
	echo "Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA"
	echo
	echo "Syntax: butler [DEPARTMENT/TASK]"
	echo "Available departments:"
	echo "admin  Administrative Tasks"
	echo "fun    Fun Tasks"
	echo "net    Network/Internet Tasks"
	echo "pkg    Package Management Tasks"
	echo "prod   Productivity Tasks"
	echo
	echo "A yad powered GUI interface is available with this command:"
	echo "butler prod/butleryad"
}

butlerlang() {
	if [ -f "/usr/share/sapphire-butler/i18n/$1/$LANG" ]; then
		source /usr/share/sapphire-butler/i18n/$1/$LANG
	elif [ -f "/usr/share/sapphire-butler/i18n/$1/en_US.utf8" ]; then
		source /usr/share/sapphire-butler/i18n/$1/en_US.utf8
	elif [ -f "/usr/share/sapphire-butler/i18n/$1/en_US.UTF-8" ]; then
		source /usr/share/sapphire-butler/i18n/$1/en_US.UTF-8
	else
		source /usr/share/sapphire-butler/i18n/$1/*
	fi
}

butlerrun() {
	butlerlang $1
	butlermsg "Running task \"$name\"..."
	source /usr/share/sapphire-butler/departments/$1/task.sh
	butlermsg "Task \"$name\" completed."
}

butlermsg() {
    notify-send -u low "Sapphire Butler" "$1"
    echo -e "\033[01;36m[❖ BUTLER]\033[0m $1"
    #espeak "$1" # Cool kids use espeak.
}

if [ -n "$1" ]; then
    for tasktodo in $@; do
      	if [ -f "/usr/share/sapphire-butler/departments/$tasktodo/task.sh" ]; then
	        butlerrun "$tasktodo"
        elif [ -d "/usr/share/sapphire-butler/departments/$tasktodo" ]; then
        	echo -e "\033[01;36m[❖ BUTLER]\033[0m Available tasks in the $tasktodo department:"
		declare -a tasksearchresults=($(find "/usr/share/sapphire-butler/departments/$tasktodo/" -name task.sh | sed -e 's/\/usr\/share\/sapphire-butler\/departments\///g' -e 's/\/task.sh//g'))
		printf "\t%-30s %-30s" "Name" "Department/Task"
		echo -e "\n------------------------------------------------------------"
		for tasksearch in ${tasksearchresults[@]}; do
			butlerlang $tasksearch
			printf "%-30s %-30s" "$name" "$tasksearch"
			echo
		done
        else
        	didyoumean=$(find "/usr/share/sapphire-butler/departments/" -iname "$tasktodo" | sed 's/\/usr\/share\/sapphire-butler\/departments\///g')
	        if [ -f "/usr/share/sapphire-butler/departments/$didyoumean/task.sh" ]; then
	        	echo -e "\033[01;36m[❖ BUTLER]\033[0m Did you mean to run:"
	        	echo "butler $didyoumean"
	        else
	        	echo -e "\033[01;36m[❖ BUTLER]\033[0m $tasktodo is not a valid department or task."
	        fi
        fi
    done
else
    m_help
fi
